<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Contact;
use yii\helpers\ArrayHelper;

/**
 * PersonSearch represents the model behind the search form of `app\models\Contact`.
 */
class ContactSearch extends Contact
{
    /**
     * @var string フォーム名
     */
    public $_form_name = 'cs';

    use LoadParamsTrait;

    public $search_name;

    public $search_phone;

    public $p_type;

    /**
     * @return string フォーム名
     * @throws \yii\base\InvalidConfigException
     */
    public function formName()
    {
        return $this->_form_name;
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(
            parent::attributeLabels(),
            [
                'search_name' => '氏名／名称',
                'search_phone' => '電話番号',
                'p_type' => 'タイプ',
            ]); // TODO: Change the autogenerated stub
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'person_id', 'order', 'created_by', 'updated_by'], 'integer'],
            [['name1', 'name2', 'name', 'role', 'p_type', 'zip', 'address1', 'address2', 'phone1', 'phone2', 'search_name', 'search_phone', 'mail', 'note', 'created_at', 'updated_at'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     * @param string|null $formName Form name to be used into `->load()` method.
     *
     * @return ActiveDataProvider
     */
    public function search($params, $pageSize = 20, $sessionKey = null)
    {
        $params = $this->rememberGridParams($params, 'c-page', 'c-sort', $sessionKey);

        $query = Contact::find()->joinWith('person');

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageParam' => 'c-page',
                'params'    => $params,
                'pageSize' => $pageSize,
            ],
            'sort' => [
                'sortParam' => 'c-sort',
                'params'    => $params,
                'defaultOrder' => ['person.name' => SORT_ASC],
                'attributes' => [
                    'person.type' => [
                        'asc' => ['person.type' => SORT_ASC, 'person.yomi' => SORT_ASC, 'contact.order' => SORT_ASC],
                        'desc' => ['person.type' => SORT_DESC, 'person.yomi' => SORT_DESC, 'contact.order' => SORT_ASC],
                    ],
                    'person.name' => [
                        'asc' => ['person.yomi' => SORT_ASC, 'contact.order' => SORT_ASC],
                        'desc' => ['person.yomi' => SORT_DESC, 'contact.order' => SORT_ASC],
                    ],
                    'contact_name' => [
                        'asc' => ['contact.name' => SORT_ASC, 'person.yomi' => SORT_ASC],
                        'desc' => ['contact.name' => SORT_DESC, 'person.yomi' => SORT_ASC],
                    ],
                    'zip' => [
                        'asc' => ['zip' => SORT_ASC, 'address1' => SORT_ASC, 'address2' => SORT_ASC],
                        'desc' => ['zip' => SORT_DESC, 'address1' => SORT_DESC, 'address2' => SORT_DESC],
                    ],
                    'address1' => [
                        'asc' => ['address1' => SORT_ASC, 'address2' => SORT_ASC],
                        'desc' => ['address1' => SORT_DESC, 'address2' => SORT_DESC],
                    ],
                    'phone1',
                    'phone2',
                    'note' => [
                        'asc' => ['contact.note' => SORT_ASC, 'address1' => SORT_ASC, 'address2' => SORT_ASC],
                        'desc' => ['contact.note' => SORT_DESC, 'address1' => SORT_ASC, 'address2' => SORT_ASC],
                    ],
                    'mail',
                ],
            ],
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'person.type' => $this->p_type,
            'created_at' => $this->created_at,
            'created_by' => $this->created_by,
            'updated_at' => $this->updated_at,
            'updated_by' => $this->updated_by,
        ]);

        $query->andFilterWhere(['ilike', 'contact.name', $this->name])
            ->andFilterWhere(['ilike', 'contact.name1', $this->name1])
            ->andFilterWhere(['ilike', 'contact.name2', $this->name2])
            ->andFilterWhere(['ilike', 'role', $this->role])
            ->andFilterWhere(['ilike', 'address1', $this->address1])
            ->andFilterWhere(['ilike', 'phone1', $this->phone1])
            ->andFilterWhere(['ilike', 'phone2', $this->phone2])
            ->andFilterWhere(['ilike', 'mail', $this->mail])
            ->andFilterWhere(['ilike', 'contact.note', $this->note]);

        if ($this->search_phone != '') {
            $query->andWhere(['or',
                ['ilike', 'phone1', $this->search_phone],
                ['ilike', 'phone2', $this->search_phone]
            ]);
        }
        if ($this->search_name != '') {
            $query->andWhere(['or',
                ['ilike', 'contact.name', $this->search_name],
                ['ilike', 'person.name', $this->search_name],
                ['ilike', 'person.yomi', $this->search_name]
            ]);
        }
        return $dataProvider;
    }
}
