<?php

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Contact;
use yii\helpers\ArrayHelper;

/**
 * PersonSearch represents the model behind the search form of `app\models\Contact`.
 */
class ContactSearch extends Contact
{
    /**
     * @var string フォーム名
     */
    public $_form_name = 'cs';

    use LoadParamsTrait;

    public $search_phone;

    /**
     * @return string フォーム名
     * @throws \yii\base\InvalidConfigException
     */
    public function formName()
    {
        return $this->_form_name;
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(
            parent::attributeLabels(),
            [
                'search_address' => '住所',
                'search_phone' => '電話番号'
            ]); // TODO: Change the autogenerated stub
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'created_by', 'updated_by'], 'integer'],
            [['zip', 'address1', 'address2', 'phone1', 'phone2', 'mail', 'note', 'created_at', 'updated_at'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     * @param string|null $formName Form name to be used into `->load()` method.
     *
     * @return ActiveDataProvider
     */
    public function search($params, $pageSize = 20)
    {
        $query = Contact::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => $pageSize,
            ],
            'sort' => [
                'defaultOrder' => ['address1' => SORT_ASC],
                'attributes' => [
                    'zip' => [
                        'asc' => ['zip' => SORT_ASC, 'address1' => SORT_ASC],
                        'desc' => ['zip' => SORT_DESC, 'address1' => SORT_DESC],
                    ],
                    'address1',
                    'phone1',
                    'phone2',
                    'note' => [
                        'asc' => ['note' => SORT_ASC, 'address1' => SORT_ASC],
                        'desc' => ['note' => SORT_DESC, 'address1' => SORT_ASC],
                    ],
                    'mail',
                ],
            ],
        ]);

        $this->loadAndRememberParams($this, $dataProvider, $params);
        // $this->load($params, $formName);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'created_at' => $this->created_at,
            'created_by' => $this->created_by,
            'updated_at' => $this->updated_at,
            'updated_by' => $this->updated_by,
        ]);

        $query->andFilterWhere(['ilike', 'address1', $this->address1])
            ->andFilterWhere(['ilike', 'phone1', $this->phone1])
            ->andFilterWhere(['ilike', 'phone2', $this->phone2])
            ->andFilterWhere(['ilike', 'mail', $this->mail])
            ->andFilterWhere(['ilike', 'note', $this->note]);

        if ($this->search_phone != '') {
            $query->andWhere(['or',
                ['ilike', 'phone1', $this->search_phone],
                ['ilike', 'phone2', $this->search_phone]
            ]);
        }
        return $dataProvider;
    }
}
