<?php

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Forest;
use yii\helpers\ArrayHelper;

/**
 * ForestSearch represents the model behind the search form of `app\models\Forest`.
 */
class ForestSearch extends Forest
{
    public string $_form_name = 'fs';

    use LoadParamsTrait;

    public ?string $search_name = null;

    /**
     * {@inheritdoc}
     */
    public function rules(): array
    {
        return [
            [['id', 'aza_id', 'type_id', 'created_by', 'updated_by'], 'integer'],
            [['geom', 'p_no', 'note', 'search_name', 'created_at', 'updated_at'], 'safe'],
            [['area'], 'number'],
        ];
    }

    public function attributeLabels(): array
    {
        return ArrayHelper::merge(
            parent::attributeLabels(),
            [
                'search_name' => '所有者・管理者',
            ]); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     * @param string|null $formName Form name to be used into `->load()` method.
     *
     * @return ActiveDataProvider
     */
    public function search($params,  $pageSize = 20)
    {
        $query = Forest::find()
            ->leftJoin('aza a', 'a.id = forest.aza_id')
            ->leftJoin('frtype ft', 'ft.id = forest.type_id')
            ->leftJoin('forest_person fpo', 'fpo.forest_id = forest.id and fpo.role = 1 and fpo.valid_to IS null')
            ->leftJoin('person po', 'po.id = fpo.person_id')
            ->leftJoin('forest_person fpm', 'fpm.forest_id = forest.id and fpm.role = 2 and fpm.valid_to IS null')
            ->leftJoin('person pm', 'pm.id = fpm.person_id');

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'defaultOrder' => ['p_no' => SORT_ASC],
                'attributes' => [
                    'aza_id' => [
                        'asc' => ['a.name' => SORT_ASC, 'p_no' => SORT_ASC],
                        'desc' => ['a.name' => SORT_DESC, 'p_no' => SORT_ASC],
                    ],
                    'p_no',
                    'type_id' => [
                        'asc' => ['ft.order' => SORT_ASC, 'p_no' => SORT_ASC],
                        'desc' => ['ft.order' => SORT_DESC, 'p_no' => SORT_ASC],
                    ],
                    'owner' => [
                        'asc' => ['po.yomi' => SORT_ASC, 'p_no' => SORT_ASC],
                        'desc' => ['po.yomi' => SORT_DESC, 'p_no' => SORT_ASC],
                    ],
                    'manager' => [
                        'asc' => ['pm.yomi' => SORT_ASC, 'p_no' => SORT_ASC],
                        'desc' => ['pm.yomi' => SORT_DESC, 'p_no' => SORT_ASC],
                    ],
                    'area',
                    'note',
                ]
            ]
        ]);

        $this->loadAndRememberParams($this, $dataProvider, $params);
        // $this->load($params, $formName);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'aza_id' => $this->aza_id,
            'type_id' => $this->type_id,
            'area' => $this->area,
            'created_at' => $this->created_at,
            'created_by' => $this->created_by,
            'updated_at' => $this->updated_at,
            'updated_by' => $this->updated_by,
        ]);

        $query->andFilterWhere(['ilike', 'geom', $this->geom])
            ->andFilterWhere(['ilike', 'p_no', $this->p_no])
            ->andFilterWhere(['ilike', 'note', $this->note]);

        if ($this->search_name != '') {
            $query->andWhere(['or',
                ['ilike', 'po.name', $this->search_name],
                ['ilike', 'pm.name', $this->search_name],
                ['ilike', 'po.yomi', $this->search_name],
                ['ilike', 'pm.yomi', $this->search_name]
            ]);
        }

        return $dataProvider;
    }

    public static function getAreaTotal($dataProvider)
    {
        $query = clone($dataProvider->query);
        return $query->limit(-1)->offset(-1)->orderBy([])->sum('area');
    }
}
