<?php

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Forest;
use yii\helpers\ArrayHelper;

/**
 * ForestSearch represents the model behind the search form of `app\models\Forest`.
 */
class ForestSearch extends Forest
{
    use LoadParamsTrait;

    public $search_name;

    public $search_address;

    public function attributeLabels()
    {
        return ArrayHelper::merge(
            parent::attributeLabels(),
            [
                'search_name' => '名前',
                'search_address' => '住所'
            ]); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['geom', 'p_no', 'o_aza', 'ko_aza', 'type', 'owner', 'o_addr', 'm_addr', 'manager', 'memo', 'o_type', 'search_name', 'search_address'], 'safe'],
            [['area'], 'number'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     * @param string|null $formName Form name to be used into `->load()` method.
     *
     * @return ActiveDataProvider
     */
    public function search($params, $formName = null)
    {
        $query = Forest::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'defaultOrder' => ['p_no' => SORT_ASC],
                'attributes' => [
                    'ko_aza',
                    'p_no',
                    'owner',
                    'manager',
                    'area',
                    'type',
                ],
            ],
        ]);

        $this->loadAndRememberParams($this, $dataProvider, $params);
        // $this->load($params, $formName);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'area' => $this->area,
        ]);

        $query->andFilterWhere(['ilike', 'geom', $this->geom])
            ->andFilterWhere(['ilike', 'p_no', $this->p_no])
            ->andFilterWhere(['ilike', 'o_aza', $this->o_aza])
            ->andFilterWhere(['ilike', 'ko_aza', $this->ko_aza])
            ->andFilterWhere(['ilike', 'type', $this->type])
            ->andFilterWhere(['ilike', 'owner', $this->owner])
            ->andFilterWhere(['ilike', 'o_addr', $this->o_addr])
            ->andFilterWhere(['ilike', 'm_addr', $this->m_addr])
            ->andFilterWhere(['ilike', 'manager', $this->manager])
            ->andFilterWhere(['ilike', 'memo', $this->memo])
            ->andFilterWhere(['ilike', 'o_type', $this->o_type]);

        if ($this->search_name != '') {
            $query->andWhere(['or',
                ['ilike', 'owner', $this->search_name],
                ['ilike', 'manager', $this->search_name],
            ]);
        }
        if ($this->search_address != '') {
            $query->andWhere(['or',
                ['ilike', 'o_adrs', $this->search_address],
                ['ilike', 'm_adrs', $this->search_address]
            ]);
        }
        return $dataProvider;
    }
}
