<?php

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\PersonWork;
use yii\helpers\ArrayHelper;

/**
 * PersonWorkSearch represents the model behind the search form of `app\models\PersonWork`.
 */
class PersonWorkSearch extends PersonWork
{
    use LoadParamsTrait;

    const ALL = 0;
    const YET = 1;
    const DONE = 2;

    public $status = self::ALL;

    public static function getStatusList()
    {
        return [
            self::ALL => '全て',
            self::YET => '未処理',
            self::DONE => '処理済み',
        ];
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(
            parent::attributeLabels(),
            [
                'status' => '状態',
            ]); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'person_id', 'status'], 'integer'],
            [['name', 'address'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     * @param string|null $formName Form name to be used into `->load()` method.
     *
     * @return ActiveDataProvider
     */
    public function search($params, $formName = null)
    {
        $query = PersonWork::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'defaultOrder' => ['name' => SORT_ASC],
                'attributes' => [
                    'name' => [
                        'asc' => ['name' => SORT_ASC, 'address' => SORT_ASC],
                        'desc' => ['name' => SORT_DESC, 'address' => SORT_DESC],
                    ],
                    'address' => [
                        'asc' => ['address' => SORT_ASC, 'name' => SORT_ASC],
                        'desc' => ['address' => SORT_DESC, 'name' => SORT_DESC],
                    ],
                    'person_id',
                    'state' => [
                        'asc' => ['state' => SORT_ASC, 'name' => SORT_ASC],
                        'desc' => ['state' => SORT_DESC, 'name' => SORT_DESC],
                    ],
                ],
            ],
        ]);

        $this->loadAndRememberParams($this, $dataProvider, $params);
        // $this->load($params, $formName);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'person_id' => $this->person_id,
        ]);

        $query->andFilterWhere(['ilike', 'name', $this->name])
            ->andFilterWhere(['ilike', 'address', $this->address]);

        if ($this->status == self::YET) {
            $query->andWhere(['person_id' => null]);
        } else if ($this->status == self::DONE) {
            $query->andWhere(['not', ['person_id' => null]]);
        }

        return $dataProvider;
    }
}
