<?php

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Person;
use yii\helpers\ArrayHelper;

/**
 * PersonSearch represents the model behind the search form of `app\models\Person`.
 */
class PersonSearch extends Person
{
    /**
     * @var string フォーム名
     */
    public $_form_name = 'ps';

    use LoadParamsTrait;

    public $search_name;

    public $search_phone;

    /**
     * @return string フォーム名
     * @throws \yii\base\InvalidConfigException
     */
    public function formName()
    {
        return $this->_form_name;
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(
            parent::attributeLabels(),
            [
                'search_name' => '名前',
                'search_phone' => '電話番号'
            ]); // TODO: Change the autogenerated stub
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'created_by', 'updated_by'], 'integer'],
            [['search_name', 'address', 'search_phone', 'memo'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     * @param string|null $formName Form name to be used into `->load()` method.
     *
     * @return ActiveDataProvider
     */
    public function search($params, $pageSize = 20)
    {
        $query = Person::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => $pageSize,
            ],
            'sort' => [
                'defaultOrder' => ['name' => SORT_ASC],
                'attributes' => [
                    'name',
                    'phone1',
                    'phone2',
                    'zip' => [
                        'asc' => ['zip' => SORT_ASC, 'address' => SORT_ASC],
                        'desc' => ['zip' => SORT_DESC, 'address' => SORT_DESC],
                    ],
                    'address',
                    'memo' => [
                        'asc' => ['memo' => SORT_ASC, 'name' => SORT_ASC],
                        'desc' => ['memo' => SORT_DESC, 'name' => SORT_ASC],
                    ],
                ],
            ],
        ]);

        $this->loadAndRememberParams($this, $dataProvider, $params);
        // $this->load($params, $formName);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'created_at' => $this->created_at,
            'created_by' => $this->created_by,
            'updated_at' => $this->updated_at,
            'updated_by' => $this->updated_by,
        ]);

        $query->andFilterWhere(['ilike', 'name1', $this->name1])
            ->andFilterWhere(['ilike', 'name2', $this->name2])
            ->andFilterWhere(['ilike', 'yomi1', $this->yomi1])
            ->andFilterWhere(['ilike', 'yomi2', $this->yomi2])
            ->andFilterWhere(['ilike', 'address', $this->address])
            ->andFilterWhere(['ilike', 'phone1', $this->phone1])
            ->andFilterWhere(['ilike', 'phone2', $this->phone2])
            ->andFilterWhere(['ilike', 'memo', $this->memo]);

        if ($this->search_name != '') {
            $query->andWhere(['or',
                ['ilike', 'name', $this->search_name],
                ['ilike', 'yomi', $this->search_name],
            ]);
        }
        if ($this->search_phone != '') {
            $query->andWhere(['or',
                ['ilike', 'phone1', $this->search_phone],
                ['ilike', 'phone2', $this->search_phone]
            ]);
        }
        return $dataProvider;
    }
}
